from enum import Enum

class Producao(Enum):

    PROGRAM = 1
    DECLARATION_LIST = 2
    DECLARATION_LIST_LINHA = 3
    DECLARATION = 4
    VAR_DECLARATION = 5
    TYPE_SPECIFIER = 6
    FUN_DECLARATION = 7
    PARAMS = 8
    PARAM_LIST = 9
    PARAM_LIST_LINHA = 10
    PARAM = 11
    COMPOUND_STMT = 12
    LOCAL_DECLARATIONS = 13
    LOCAL_DECLARATIONS_LINHA = 14
    STATEMENT_LIST = 15
    STATEMENT_LIST_LINHA = 16
    STATEMENT = 17
    EXPRESSION_STMT = 18
    SELECTION_STMT = 19
    ITERATION_STMT = 20
    RETURN_STMT = 21
    EXPRESSION = 22
    VAR = 23
    SIMPLE_EXPRESSION = 24
    RELOP = 25
    ADDITIVE_EXPRESSION = 26
    ADDITIVE_EXPRESSION_LINHA = 27
    ADDOP = 28
    TERM = 29
    TERM_LINHA = 30
    MULOP = 31
    FACTOR = 32
    CALL = 33
    ARGS = 34
    ARG_LIST = 35
    ARG_LIST_LINHA = 36
